from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
import uuid
class Migration(migrations.Migration):
 initial=True
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='Course',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('slug',models.SlugField(unique=True)),('description',models.TextField()),('level',models.CharField(default='Intermediate',max_length=30)),('duration_hours',models.PositiveIntegerField(default=10)),('published',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
  migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(default='student',max_length=20)),('headline',models.CharField(blank=True,max_length=160)),('target_role',models.CharField(default='Full Stack AI Developer',max_length=100)),('readiness',models.PositiveIntegerField(default=72)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='InterviewQuestion',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('question',models.TextField()),('answer',models.TextField()),('topic',models.CharField(max_length=80)),('difficulty',models.CharField(default='Medium',max_length=20)),('is_active',models.BooleanField(default=True))]),
  migrations.CreateModel(name='Enrollment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('progress',models.PositiveIntegerField(default=0)),('completed',models.BooleanField(default=False)),('updated_at',models.DateTimeField(auto_now=True)),('course',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='enrollments',to='core.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='enrollments',to=settings.AUTH_USER_MODEL))],options={'unique_together':{('user','course')}}),
  migrations.CreateModel(name='Attempt',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('answer',models.TextField(blank=True)),('score',models.PositiveIntegerField(default=0)),('feedback',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('question',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.interviewquestion')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='Certificate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('certificate_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('issued_at',models.DateTimeField(auto_now_add=True)),('course',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.course')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='MentorSession',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('mentor_name',models.CharField(max_length=100)),('topic',models.CharField(max_length=160)),('status',models.CharField(default='requested',max_length=30)),('scheduled_for',models.DateTimeField(blank=True,null=True)),('learner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='mentor_sessions',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='ProjectSubmission',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('description',models.TextField()),('repo_url',models.URLField(blank=True)),('status',models.CharField(default='submitted',max_length=30)),('score',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='AIRecommendation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(max_length=50)),('title',models.CharField(max_length=160)),('reason',models.TextField()),('priority',models.PositiveIntegerField(default=3)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
 ]
