import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate,useParams} from 'react-router-dom';
import * as Icons from 'lucide-react';
import './style.css';
import V4CommandCenter from './upgrades/V4CommandCenter.jsx';
import './upgrades/v3.css';
import V3CommandCenter from './upgrades/V3CommandCenter.jsx';

const API=import.meta.env.VITE_API_URL||'/api';
const token=()=>localStorage.getItem('esh_access');
function saveSession(data){localStorage.setItem('esh_access',data.access);if(data.refresh)localStorage.setItem('esh_refresh',data.refresh);if(data.user)localStorage.setItem('esh_user',JSON.stringify(data.user));}
function clearSession(){localStorage.removeItem('esh_access');localStorage.removeItem('esh_refresh');localStorage.removeItem('esh_user');}


const groups=[
 {id:'v3',label:'V3 Command Center',icon:'Sparkles',pages:['v3']},
 {id:'foundation',label:'Foundation',icon:'GraduationCap',pages:['dashboard','profile','resume','resume-score','english','english-vocab','english-speaking','interview-english','communication','career-goals']},
 {id:'python',label:'Python & OOP',icon:'Code2',pages:['python-roadmap','python-basics','python-datatypes','python-functions','python-modules','python-exceptions','python-files','python-oop','python-advanced','python-lab']},
 {id:'web',label:'Web & React',icon:'Globe2',pages:['html5','css3','javascript','javascript-async','react','react-hooks','react-state','react-routing','frontend-lab','ui-system']},
 {id:'backend',label:'Django & APIs',icon:'Server',pages:['django','django-models','django-orm','django-auth','drf','rest-api','api-security','api-testing','backend-lab','backend-architecture']},
 {id:'data',label:'SQL & Data',icon:'Database',pages:['sql','mysql','dbms','database-design','sql-optimization','transactions','nosql','data-lab','analytics','data-architecture']},
 {id:'ai',label:'AI Engineering',icon:'BrainCircuit',pages:['ai-roadmap','ai-fundamentals','prompt-engineering','ai-recommendations','rag','embeddings','vector-search','ai-agents','ai-evaluation','ai-lab']},
 {id:'project',label:'EntreSkill Hub',icon:'Rocket',pages:['project-overview','project-architecture','project-auth','project-courses','project-enrollment','project-progress','project-interviews','project-certificates','project-mentorship','project-ai']},
 {id:'devops',label:'Cloud & DevOps',icon:'CloudCog',pages:['git','github','docker','docker-compose','ci-cd','github-actions','azure','aws','kubernetes','deployment']},
 {id:'dsa',label:'DSA & Coding',icon:'Binary',pages:['dsa-roadmap','complexity','arrays','strings','hashing','linked-list','stack-queue','trees','graphs','dynamic-programming']},
 {id:'interview',label:'Interview Arena',icon:'Trophy',pages:['mock-dashboard','mock-python','mock-django','mock-react','mock-sql','mock-system-design','mock-project','coding-round','hr-round','final-interview']}
];
const pageMeta={
 dashboard:['Command Center','Your full-stack AI developer control room'],profile:['Profile','Professional identity and developer profile'],resume:['Resume Studio','Build a truthful, ATS-friendly developer resume'],['resume-score']:['Resume Score','Score every section against interview readiness'],english:['English Interview','Technical English foundations'],['english-vocab']:['Technical Vocabulary','High-frequency interview vocabulary'],['english-speaking']:['Speaking Lab','Timed technical speaking practice'],['interview-english']:['Interview English','Answer patterns for technical interviews'],communication:['Communication','Explain technical ideas clearly'],['career-goals']:['Career Goals','10 LPA-oriented development targets'],
['python-roadmap']:['Python Roadmap','From syntax to production Python'],['python-basics']:['Python Basics','Core syntax and logic'],['python-datatypes']:['Python Data Types','List, tuple, set, dict and beyond'],['python-functions']:['Functions','Reusable program logic'],['python-modules']:['Modules & Packages','Organize production code'],['python-exceptions']:['Exception Handling','Reliable error management'],['python-files']:['File Handling','Read, write and process files'],['python-oop']:['Python OOP','Classes, inheritance and design'],['python-advanced']:['Advanced Python','Decorators, generators and internals'],['python-lab']:['Python Lab','Run interview-style coding challenges'],
html5:['HTML5','Semantic web structure'],css3:['CSS3','Modern responsive styling'],javascript:['JavaScript','Core language and browser logic'],['javascript-async']:['Async JavaScript','Promises, async/await and event loop'],react:['React.js','Component-driven frontend'],['react-hooks']:['React Hooks','useState, useEffect and custom hooks'],['react-state']:['State Management','Predictable application state'],['react-routing']:['React Routing','Connected multi-page SPA navigation'],['frontend-lab']:['Frontend Lab','Build UI features interactively'],['ui-system']:['UI System','Reusable design components'],
django:['Django','Production Python web framework'],['django-models']:['Django Models','Design persistent application data'],['django-orm']:['Django ORM','Query data without raw SQL'],['django-auth']:['Django Auth','Authentication and permissions'],drf:['Django REST Framework','Build production APIs'],['rest-api']:['REST API','Resource-oriented API design'],['api-security']:['API Security','Secure production endpoints'],['api-testing']:['API Testing','Validate backend contracts'],['backend-lab']:['Backend Lab','Practice backend implementation'],['backend-architecture']:['Backend Architecture','Structure scalable services'],
sql:['SQL','Query and manipulate relational data'],mysql:['MySQL','Relational database engineering'],dbms:['DBMS','Database fundamentals'],['database-design']:['Database Design','Relationships, normalization and schema'],['sql-optimization']:['SQL Optimization','Indexes and query performance'],transactions:['Transactions','ACID and concurrency'],nosql:['NoSQL','When relational is not enough'],['data-lab']:['Data Lab','SQL and data challenges'],analytics:['Analytics','Turn data into decisions'],['data-architecture']:['Data Architecture','Reliable data flows'],
['ai-roadmap']:['AI Engineering Roadmap','Build AI features as a full-stack developer'],['ai-fundamentals']:['AI Fundamentals','Core concepts without hype'],['prompt-engineering']:['Prompt Engineering','Structured prompts and evaluation'],['ai-recommendations']:['AI Recommendations','Personalized career and learning engine'],rag:['RAG','Retrieval-augmented generation'],embeddings:['Embeddings','Represent meaning as vectors'],['vector-search']:['Vector Search','Semantic retrieval architecture'],['ai-agents']:['AI Agents','Tool-using AI workflows'],['ai-evaluation']:['AI Evaluation','Measure quality and reliability'],['ai-lab']:['AI Lab','Build AI feature prototypes'],
['project-overview']:['EntreSkill Hub','Portfolio-grade product overview'],['project-architecture']:['Architecture','End-to-end platform architecture'],['project-auth']:['Authentication','JWT/OAuth2/RBAC flow'],['project-courses']:['Courses','Learning catalogue and content'],['project-enrollment']:['Enrollment','Join and manage learning paths'],['project-progress']:['Progress','Track learning and assessments'],['project-interviews']:['Interview Portal','MCQ, technical and project rounds'],['project-certificates']:['Certificates','Completion and verification'],['project-mentorship']:['Mentorship','Connect learners and mentors'],['project-ai']:['AI Career Engine','Recommendations and roadmaps'],
git:['Git','Version control fundamentals'],github:['GitHub','Collaboration and source control'],docker:['Docker','Containerize the platform'],['docker-compose']:['Docker Compose','Run multi-service development'],['ci-cd']:['CI/CD','Automated delivery pipelines'],['github-actions']:['GitHub Actions','Workflow automation'],azure:['Azure','Cloud deployment concepts'],aws:['AWS','Cloud platform fundamentals'],kubernetes:['Kubernetes','Container orchestration'],deployment:['Deployment','Production release checklist'],
['dsa-roadmap']:['DSA Roadmap','Interview problem-solving path'],complexity:['Complexity','Big-O reasoning'],arrays:['Arrays','Patterns and problems'],strings:['Strings','String algorithms'],hashing:['Hashing','Fast lookup patterns'],['linked-list']:['Linked List','Pointer-based structures'],['stack-queue']:['Stack & Queue','LIFO/FIFO patterns'],trees:['Trees','Hierarchical data structures'],graphs:['Graphs','Traversal and shortest paths'],['dynamic-programming']:['Dynamic Programming','Optimize overlapping subproblems'],
['mock-dashboard']:['Interview Arena','Live readiness dashboard'],['mock-python']:['Python Mock','Python technical round'],['mock-django']:['Django Mock','Backend technical round'],['mock-react']:['React Mock','Frontend technical round'],['mock-sql']:['SQL Mock','Database technical round'],['mock-system-design']:['System Design Mock','Architecture round'],['mock-project']:['Project Mock','EntreSkill Hub deep dive'],['coding-round']:['Coding Round','Timed coding interview'],['hr-round']:['HR Round','Behavioral interview'],['final-interview']:['Final Interview','Full 10 LPA simulation']
};
pageMeta.v3=['V3 AI Developer Command Center','Premium AI developer career command center'];
const v4Page={id:'v4',title:'V4 AI Command Center'};
const allPages=groups.flatMap(g=>g.pages);
const title=(id)=>pageMeta[id]?.[0]||id.replaceAll('-',' ');

function Icon({name,size=18}){const C=Icons[name]||Icons.Circle;return <C size={size}/>}
function apiFetch(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;return fetch(`${API}${path}`,{...options,headers}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||'API request failed');return d})}

function AuthScreen({onAuth}){
 const [mode,setMode]=useState('login'); const [form,setForm]=useState({username:'demo',password:'Demo@12345',email:''}); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const path=mode==='login'?'/token/':'/register/';const data=await apiFetch(path,{method:'POST',body:JSON.stringify(form)});saveSession(data);if(!data.user){const u=await apiFetch('/profile/');localStorage.setItem('esh_user',JSON.stringify(u.user));}onAuth()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="authscreen"><div className="authcard"><div className="brand authbrand"><div className="brandmark"><Icon name="Sparkles"/></div><div><b>EntreSkill Hub</b><span>FULL STACK AI DEVELOPER</span></div></div><div className="eyebrow"><span className="dot"/> V2 PRODUCTION WORKSPACE</div><h1>{mode==='login'?'Welcome back':'Create developer account'}</h1><p>{mode==='login'?'Continue your 10 LPA interview-ready learning track.':'Create a student workspace and start the connected learning flow.'}</p><form onSubmit={submit}><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} minLength={3} required/></label>{mode==='register'&&<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>}<label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={8} required/></label>{error&&<div className="autherror">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Connecting…':mode==='login'?'Sign in':'Create account'} <Icon name="ArrowRight" size={16}/></button></form><div className="authswitch">{mode==='login'?<>New here? <button onClick={()=>{setMode('register');setForm({username:'',password:'',email:''})}}>Create account</button></>:<>Already registered? <button onClick={()=>{setMode('login');setForm({username:'demo',password:'Demo@12345',email:''})}}>Sign in</button></>}</div><div className="demo">Demo account: <b>demo</b> / <b>Demo@12345</b></div></div></div>
}

function App(){
 const location=useLocation(),navigate=useNavigate();
 const [authed,setAuthed]=useState(!!token()); const [dark,setDark]=useState(true); const [open,setOpen]=useState(true); const [search,setSearch]=useState(''); const [toast,setToast]=useState(''); const [me,setMe]=useState(()=>{try{return JSON.parse(localStorage.getItem('esh_user'))||null}catch{return null}});
 const slug=location.pathname.split('/').filter(Boolean).pop()||'dashboard'; const current=allPages.includes(slug)?slug:'dashboard';
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(authed){apiFetch('/profile/').then(d=>setMe(d.user)).catch(()=>{clearSession();setAuthed(false)})}},[authed]);
 const filtered=useMemo(()=>allPages.filter(p=>title(p).toLowerCase().includes(search.toLowerCase())).slice(0,10),[search]);
 const group=groups.find(g=>g.pages.includes(current))||groups[0]; const idx=allPages.indexOf(current); const prev=allPages[(idx-1+allPages.length)%allPages.length]; const next=allPages[(idx+1)%allPages.length];
 if(!authed)return <AuthScreen onAuth={()=>{setAuthed(true);setToast('Secure session created')}}/>;
 const logout=()=>{clearSession();setAuthed(false);setMe(null);navigate('/dashboard')};
 return <div className="app">
   <aside className={`sidebar ${open?'open':''}`}>
    <div className="brand"><div className="brandmark"><Icon name="Sparkles"/></div><div><b>EntreSkill</b><span>HUB • AI DEVELOPER</span></div></div>
    <div className="workspace"><div className="avatar">{(me?.username||'DG').slice(0,2).toUpperCase()}</div><div><b>{me?.username||'Developer'}</b><span>{me?.role||'student'} • 10 LPA Track</span></div><Icon name="ChevronDown" size={15}/></div>
    <nav>{groups.map(g=><div key={g.id} className="navgroup"><div className="navtitle"><Icon name={g.icon} size={15}/>{g.label}</div>{g.pages.map(p=><button key={p} onClick={()=>navigate('/'+p)} className={current===p?'active':''}><span>{title(p)}</span>{current===p&&<i/>}</button>)}</div>)}</nav>
    <div className="sidebarBottom"><button onClick={()=>setToast('V2 settings are API-connected')}><Icon name="Settings"/> Settings</button><button onClick={logout}><Icon name="LogOut"/> Sign out</button></div>
   </aside>
   <main className="main">
    <header className="topbar"><button className="iconbtn" onClick={()=>setOpen(!open)}><Icon name="PanelLeft"/></button><div className="crumb">{group.label} <span>/</span> {title(current)}</div><div className="topactions"><div className="search"><Icon name="Search" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search 100 learning screens..."/>{search&&<div className="searchdrop">{filtered.map(p=><button key={p} onClick={()=>{navigate('/'+p);setSearch('')}}>{title(p)}<Icon name="ArrowUpRight" size={14}/></button>)}</div>}</div><button className="iconbtn" onClick={()=>setDark(!dark)}><Icon name={dark?'Sun':'Moon'}/></button><button className="notification" onClick={()=>setToast('V2 API notifications are connected')}><Icon name="Bell"/><span>3</span></button><div className="miniavatar">{(me?.username||'DG').slice(0,2).toUpperCase()}</div></div></header>
    <section className="pagewrap"><Page page={current} onToast={setToast}/></section>
    <footer className="pager"><button onClick={()=>navigate('/'+prev)}><Icon name="ArrowLeft"/> {title(prev)}</button><div><span>{idx+1}</span> / {allPages.length}</div><button onClick={()=>navigate('/'+next)}>{title(next)} <Icon name="ArrowRight"/></button></footer>
   </main>
   {toast&&<div className="toast"><Icon name="CheckCircle2"/> {toast}</div>}
 </div>
}

function Page({page,onToast}){
  if(page==='v4') return <V4CommandCenter/>;
 if(page==='v3') return <V3CommandCenter/>;
 const [tab,setTab]=useState('Overview'); const [done,setDone]=useState(false); const [query,setQuery]=useState(''); const [score,setScore]=useState(72); const [dashboard,setDashboard]=useState(null); const [apiState,setApiState]=useState('');
 const meta=pageMeta[page]||[title(page),'Interactive learning workspace']; const isMock=page.startsWith('mock-')||page==='coding-round'||page==='final-interview'; const isProject=page.startsWith('project-'); const isAI=page.startsWith('ai-')||['rag','embeddings','vector-search'].includes(page); const isCode=['python-lab','frontend-lab','backend-lab','data-lab','ai-lab','coding-round'].includes(page);
 useEffect(()=>{if(page==='dashboard'){apiFetch('/dashboard/').then(setDashboard).catch(()=>{})}},[page]);
 const metrics=dashboard&&page==='dashboard'?[['Readiness',`${dashboard.readiness}%`,'Live API score'],['Courses',dashboard.enrollments,'Your enrollments'],['Certificates',dashboard.certificates,'Issued'],['Attempts',dashboard.attempts,'Interview attempts']]:isProject?[['Modules','100','Connected screens'],['API Contracts','24','Backend endpoints'],['Roles','3','Student/Mentor/Admin'],['AI Flows','3','Provider-ready']]:isMock?[['Readiness',`${score}%`,'Target 90%'],['Questions','5','Live bank'],['Weak Areas','7','Needs practice'],['Streak','12d','Practice target']]:[['Progress','72%','Current track'],['Lessons','48','Available now'],['Projects','12','Hands-on'],['Interview',`${score}%`,'Readiness']];
 const liveAction=async()=>{try{if(page==='dashboard'){setApiState('Dashboard refreshed from Django REST API.');}else if(page==='project-enrollment'){const courses=await apiFetch('/courses/');const first=courses.results?.[0]||courses[0];if(first){await apiFetch('/enrollments/',{method:'POST',body:JSON.stringify({course_id:first.id})});setApiState(`Enrolled in ${first.title}.`);}}else if(page==='project-progress'){const en=await apiFetch('/enrollments/');if(en.results?.length){await apiFetch(`/enrollments/${en.results[0].id}/progress/`,{method:'PATCH',body:JSON.stringify({progress:100})});setApiState('Progress updated to 100%; certificate issued if eligible.');}}else if(isAI){const r=await apiFetch('/ai/generate/',{method:'POST',body:JSON.stringify({prompt:query})});setApiState(`AI plan generated: ${r.length} recommendations saved.`);}else{setApiState('API action ready for this module.');}onToast('Saved to your V2 workspace')}catch(e){setApiState(e.message)}};
 return <div className="page"><div className="hero"><div><div className="eyebrow"><span className="dot"/> {isProject?'PORTFOLIO PROJECT':isAI?'AI ENGINEERING':isMock?'INTERVIEW ARENA':'10 LPA DEVELOPER TRACK'}</div><h1>{meta[0]}</h1><p>{meta[1]}</p><div className="heroBtns"><button className="primary" onClick={()=>{setDone(true);liveAction()}}><Icon name={done?'CheckCircle2':'Play'}/>{done?'Saved':'Start / Save'}</button><button className="secondary" onClick={()=>onToast('Interview notes copied to workspace')}><Icon name="Copy"/> Interview notes</button></div>{apiState&&<div className="apiresult"><Icon name="Database"/> {apiState}</div>}</div><div className="heroOrb"><Icon name={isAI?'BrainCircuit':isProject?'Rocket':isMock?'Trophy':'Sparkles'} size={42}/><span>V2 LIVE</span></div></div><div className="metrics">{metrics.map(m=><div className="metric" key={m[0]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[2]}</small></div>)}</div><div className="contentgrid"><section className="card maincard"><div className="cardhead"><div><span className="eyebrow">WORKSPACE</span><h2>{isMock?'Interview Simulation':isCode?'Hands-on Lab':isProject?'Product Architecture':isAI?'AI Feature Studio':'Concept → Practice → Interview'}</h2></div><div className="tabs">{['Overview','Practice','Interview'].map(t=><button className={tab===t?'sel':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div></div>{isCode?<CodeLab page={page} onToast={onToast}/>:isMock?<MockLab page={page} score={score} setScore={setScore} onToast={onToast}/>:isProject?<ProjectCanvas page={page}/>:isAI?<AILab page={page} onToast={onToast}/>:<LearningPanel page={page} tab={tab} query={query} setQuery={setQuery} onToast={onToast}/>}</section><aside className="rightcol"><div className="card"><div className="cardhead"><h3>Interview Lens</h3><Icon name="Target"/></div><div className="lens"><b>{score}%</b><span>Answer readiness</span><div className="progress"><i style={{width:`${score}%`}}/></div></div><ul className="checklist"><li><Icon name="Check"/> What / Why / How</li><li><Icon name="Check"/> Real project example</li><li><Icon name="Check"/> Code + output</li><li><Icon name="Circle"/> Cross-question drill</li></ul></div><div className="card"><div className="cardhead"><h3>Next Connections</h3><Icon name="GitBranch"/></div><div className="connections"><Connection from={page} to={allPages[(allPages.indexOf(page)+1)%allPages.length]}/><Connection from={page} to={isProject?'project-architecture':'mock-project'}/><Connection from={page} to="final-interview"/></div></div></aside></div></div>
}
function Connection({from,to}){const nav=useNavigate();return <button className="connection" onClick={()=>nav('/'+to)}><span>{title(to)}</span><Icon name="ArrowUpRight" size={15}/></button>}
function LearningPanel({page,tab,query,setQuery,onToast}){const cards=[['What','Define the concept in one sentence.'],['Why','Explain why an engineer would use it.'],['How','Describe the implementation flow.'],['Example','Connect it to EntreSkill Hub.'],['Purpose','State the business/technical goal.'],['Code','Write the smallest working example.'],['Use','Explain where it belongs in production.'],['Output','Predict what the code/system produces.']];return <><div className="questionbar"><Icon name="Sparkles"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask: explain this like an interviewer..."/><button onClick={()=>onToast('AI-ready answer workspace opened')}>Generate</button></div><div className="answergrid">{cards.map(([a,b],i)=><article key={a} className="answercard"><div className="number">{String(i+1).padStart(2,'0')}</div><h3>{a}</h3><p>{b}</p><button onClick={()=>onToast(`${a} note saved`)}>Add to interview bank <Icon name="Plus" size={14}/></button></article>)}</div><div className="coach"><Icon name="Lightbulb"/><div><b>Interview trick</b><p>Use <strong>WHAT → WHY → HOW → EXAMPLE → PURPOSE → CODE → USE → OUTPUT</strong> for every technology on your resume.</p></div></div></>}
function CodeLab({page,onToast}){const [code,setCode]=useState(page.includes('python')?'def greet(name):\n    return f"Hello {name}"\n\nprint(greet("Developer"))':'function greet(name) {\n  return `Hello ${name}`;\n}\nconsole.log(greet("Developer"));');const [out,setOut]=useState('Run the example to see output.');return <div className="lab"><div className="editor"><div className="editorbar"><span>main.code</span><button onClick={()=>{setOut('Hello Developer\n✓ Example executed successfully');onToast('Code executed in demo sandbox')}}><Icon name="Play" size={14}/> Run</button></div><textarea value={code} onChange={e=>setCode(e.target.value)}/></div><div className="output"><div className="outputhead">OUTPUT <span>DEMO RUNTIME</span></div><pre>{out}</pre><div className="test"><Icon name="CheckCircle2"/> Interview test: explain every line in 30 seconds.</div></div></div>}
function ProjectCanvas({page}){const layers=[['01','Experience','React + responsive UI'],['02','Application','Courses • Interviews • Progress'],['03','AI','Recommendations • Roadmaps • Copilot'],['04','API','Django REST • JWT • RBAC'],['05','Data','MySQL/PostgreSQL • indexes • transactions'],['06','Delivery','Docker • CI/CD • Cloud']];return <div className="architecture">{layers.map(l=><div className="layer" key={l[0]}><span>{l[0]}</span><div><b>{l[1]}</b><small>{l[2]}</small></div><Icon name="ArrowDown"/></div>)}<div className="projectflow"><span>USER</span><Icon name="ArrowRight"/><span>WEB</span><Icon name="ArrowRight"/><span>API</span><Icon name="ArrowRight"/><span>DATA</span><Icon name="ArrowRight"/><span>AI</span></div></div>}
function AILab({page,onToast}){const [input,setInput]=useState('I am a BCS fresher learning Django and React.');const [answer,setAnswer]=useState('Your next focus should be: REST APIs → authentication → project deployment.');return <div className="aiwork"><div className="promptbox"><label>AI CONTEXT</label><textarea value={input} onChange={e=>setInput(e.target.value)}/><div className="chips"><button onClick={()=>setInput('Analyze my EntreSkill Hub project for a 10 LPA interview.')}>Project review</button><button onClick={()=>setInput('Create a 7-day interview plan for this skill gap.')}>Skill gap</button><button onClick={()=>setInput('Ask me five cross-questions about this module.')}>Cross questions</button></div><button className="primary wide" onClick={()=>{setAnswer('AI-ready response: break the goal into measurable skills, implement the feature, test it, document the architecture, then practice the interview explanation.');onToast('AI response generated')}}><Icon name="Sparkles"/> Generate response</button></div><div className="aianswer"><div className="aiavatar"><Icon name="BrainCircuit"/></div><div><span className="eyebrow">ENTERSKILL AI</span><h3>Engineering Copilot</h3><p>{answer}</p><div className="sourcechips"><span>Resume</span><span>Project</span><span>Interview</span><span>Skill graph</span></div></div></div></div>}
function MockLab({page,score,setScore,onToast}){const qs=['Explain the architecture of EntreSkill Hub.','Why did you choose Django for the backend?','How does JWT authentication work?','How would you scale the platform to 100K users?','What was the hardest bug you solved?'];const [q,setQ]=useState(0);const [ans,setAns]=useState('');return <div className="mock"><div className="mockq"><span>QUESTION {q+1} / {qs.length}</span><h2>{qs[q]}</h2><textarea value={ans} onChange={e=>setAns(e.target.value)} placeholder="Speak/type your interview answer..."/><div className="mockactions"><button className="secondary" onClick={()=>onToast('Hint: use What → Why → How → Example')}>Hint</button><button className="primary" onClick={()=>{setScore(Math.min(98,score+5));setQ((q+1)%qs.length);setAns('');onToast('Answer scored and next question loaded')}}>Submit & next <Icon name="ArrowRight"/></button></div></div><div className="rubric"><h3>Scoring rubric</h3>{['Technical correctness','Project evidence','Communication','Trade-off thinking','Confidence'].map((x,i)=><div className="rubricrow" key={x}><span>{x}</span><b>{[88,74,82,66,79][i]}%</b></div>)}</div></div>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
